name: Nix Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
        with:
          diagnostic-endpoint: ""
          use-flakehub: false
      - name: Run checks
        run: nix flake check
